### ISSUE TITLE
Uninstall script

### ISSUE THREAD

**Issue by elesto** [soduto/Soduto#17]
How do I fully uninstall Soduto on macOS. I also noticed a 110mb log folder called .craft with logs in it containing craftroot and I was wondering if they were from the app. An uninstall script is needed

**Comment by giedrius-stanevicius** [comment]
Regarding .craft logs - no, it is not created by Soduto

Soduto only uses standard macOS locations to store it stuff:
~/Library/Application Scripts
~/Library/Application Support
~/Library/Containers
~/Library/Saved Application State

Look for files/directories containing "com.soduto.Soduto", "com.soduto.SodutoBrowser", "com.soduto.SodutoLauncher" or "Soduto", "Soduto Browser", "SodutoLauncher" (this seems to different across different macOS versions)  in their names
