### ISSUE TITLE
homebrew formula

### ISSUE THREAD

**Issue by jjangga0214** [soduto/Soduto#18]
Hi!

Thanks for maintaining this project!

How about providing homebrew formula?

Thanks again!

**Comment by alexanderadam** [comment]
You mean something like [`brew install --cask soduto`](https://formulae.brew.sh/cask/soduto)?

**Comment by jjangga0214** [comment]
@alexanderadam Yes, right. I didn't know there's already the formula.
That was because the README does not mention it, though it guides users building from the source.
