### ISSUE TITLE
Firewall issues?

### ISSUE THREAD

**Issue by ballo** [soduto/Soduto#25]
Hello. I switched my firewall from LuLu to Little Snitch and Soduto doesn't work reliably anymore. I can detect when the program is broadcasting to 255.255.255.255 on UDP port 1716 which I allow, but this doesn't appear to be enough. 

I've tried adding ports 1714-1764 for all protocols (presumably covering UDP & TCP) for "broadcast addresses" (which stop any prompting) for both incoming and outgoing connections. I also deleted the old devices to see if I could re-pair them which may have been a mistake. When I start it up now it prompts me to pair devices but none show up.

**Comment by giedrius-stanevicius** [comment]
Hi there. For broadcast address only 1716 port should be needed. 1716-1764 ports should be available for any local address (or to be more precise, the addresses of the devices you want to connect to)

**Comment by ballo** [comment]
I tried allowing access to all incoming and outgoing connections to soduto to no avail. I know this probably isn't a sodutu bug, but maybe if this is left up someone will find a solution.

**Comment by giedrius-stanevicius** [comment]
Here are some ideas you may want to check:
* Try initiating pairing/connection from other devices - if that worked, could be partial workaround and also could narrow the cases to check
* Try disabling the firewall - just to check if there were no any other changes in the system and that the firewall is really to blame
* Contact Little Snitch developers - maybe they could give some advices about firewall configuration/troubleshooting

**Comment by ballo** [comment]
Not sure why, but I could pair devices using a different access point (on the same network/subnet so the same IPs)

**Comment by giedrius-stanevicius** [comment]
Seems it is not relevant any more
