### ISSUE TITLE
Certificate null in KDE connect mobile app

### ISSUE THREAD

**Issue by Me-Mr** [soduto/Soduto#26]
When I checked the encryption info in the app it said SHA 256 null. 

Does this mean that the connection isn't encrypted? What's weird is that the soduto app shows an encryption key for the phone.

**Comment by giedrius-stanevicius** [comment]
This could be related with this KDE Connect bug: https://bugs.kde.org/show_bug.cgi?id=463996

**Comment by Me-Mr** [comment]
Interesting, I hope they push a fix! Thanks for your help

**Comment by giedrius-stanevicius** [comment]
Seems it is KDE Connect issue. Feel free to reopen if it is not the case.
