### ISSUE TITLE
Get the PNG icon from the payload

### ISSUE THREAD

**Issue by sannidhyaroy** [soduto/Soduto#29]
KDE Connect sends the app icon in PNG format as a payload along with the notification data packet. How can I get the image in Soduto?
I tried adding a `getAppIcon()` method inside the [`DataPacket` extension in the `NotificationsService.swift` file](https://github.com/soduto/Soduto/blob/89d672ec849a20e835a3cec13c4fd09c742a50e0/Soduto/Services/NotificationsService.swift#LL226C26-L349C26):
```
func getAppIcon() throws -> Data? {
  try self.validateNotificationType()
  guard hasPayload() else { return nil }
        
  guard let payloadStream = payload else { return nil }
        
  payloadStream.open()
  defer {
      payloadStream.close()
  }
        
  let bufferSize = 1024
  let buffer = UnsafeMutablePointer<UInt8>.allocate(capacity: bufferSize)
  defer {
      buffer.deallocate()
  }
        
  var imageData = Data()
        
  while payloadStream.hasBytesAvailable {
      let bytesRead = payloadStream.read(buffer, maxLength: bufferSize)
      if bytesRead < 0 {
          // Stream error occured
          throw payloadStream.streamError!
      } else if bytesRead == 0 {
          // End of buffer was reached
          break
      }
      imageData.append(buffer, count: bytesRead)
  }
        
  guard imageData.count == payloadSize else { return nil }
        
  return imageData
}
```
However, when I access this method from the [`showNotification()`](https://github.com/soduto/Soduto/blob/89d672ec849a20e835a3cec13c4fd09c742a50e0/Soduto/Services/NotificationsService.swift#L146) function by defining `let appIcon = try dataPacket.getAppIcon()`, nothing happens. It returns `nil` for the line `guard let payloadStream = payload else { return nil }` in the `getAppIcon()` method.

@giedrius-stanevicius Where am I going wrong? I agree I'm not very good with Swift and I didn't work with `InputStream` or similar data types in any other language either. Obviously the function above isn't entirely written by me, thanks to StackOverflow. Could you guide me a bit? I've been trying to get this to work for a couple of months but can't figure it out.

**Comment by giedrius-stanevicius** [comment]
I don't remember the codebase, so I may be wrong, but it seems you should use `dataPacket.downloadTask`, not `dataPacket.payload`. You can check the [ShareService](https://github.com/soduto/Soduto/blob/master/Soduto/Services/ShareService.swift) for example how to use it.

**Comment by sidevesh** [comment]
@sannidhyaroy @giedrius-stanevicius https://github.com/sannidhyaroy/Soduto/pull/18 I have raised this PR with some logic added towards getting the notification icon from the app show up.

**Comment by sidevesh** [comment]
@sannidhyaroy I think you can close this since we have figured out how to get the PNG icon from the payload

**Comment by sannidhyaroy** [comment]
> @sannidhyaroy I think you can close this since we have figured out how to get the PNG icon from the payload

Sure, thank you for the help.
