### ISSUE TITLE
Copy to clipboard

### ISSUE THREAD

**Issue by scottrepreneur** [soduto/Soduto#6]
Copy to/from device clipboard would be awesome!

**Comment by giedrius-stanevicius** [comment]
Clipboard content should be shared in any direction automatically, be it Computer -> Phone or Phone -> Computer. I.e. if you copy something on computer, you can paste it on the phone and vice versa. If that does not work, there might be an issue with devices connectivity (do other functions work?) or it might be software versions compatibility problem (it might be that Soduto implementation became outdated in relation with latest KDE Connect app).

**Comment by scottrepreneur** [comment]
Woah cool! Didn't realize that was available. Will try it out!

**Comment by gullitmiranda** [comment]
the clipboard sync don't work for me.

KDE Connect v1.13.7 (from play store)
Soduto 1.0.1 (11) (from https://soduto.com/downloads/)

**Comment by giedrius-stanevicius** [comment]
> the clipboard sync don't work for me.
> 
> KDE Connect v1.13.7 (from play store)
> Soduto 1.0.1 (11) (from https://soduto.com/downloads/)

* Do other functions work?
* Is it by any chance on Android 10? There seems to bee issues: https://invent.kde.org/kde/kdeconnect-android/issues/5

**Comment by gullitmiranda** [comment]
yes, its android 10 :/

**Comment by whispy** [comment]
Is it possible to disable the clipboard sync functionality?
