### ISSUE TITLE
Battery always reported as -1% or 0%

### ISSUE THREAD

**Issue by albertvaka** [soduto/Soduto#7]
When my phone connects to Soduto, I get a notification that the battery is at -1 or 0%, but this is not the case.

**Comment by giedrius-stanevicius** [comment]
Is this notification on the phone or on the desktop?

**Comment by albertvaka** [comment]
On the desktop.

**Comment by giedrius-stanevicius** [comment]
In that case I would suspect that the phone sends wrong information. Have you tried pairing the phone with Linux - does it work correctly with desktop KDE Connect?

**Comment by albertvaka** [comment]
This was indeed the phone sending the wrong values due to a race condition (that didn't happen on Linux for some reason). It's fixed here: https://invent.kde.org/kde/kdeconnect-android/-/commit/cff55ab8dd1b07e902cd6a51aef890c963f1867c
